# import cppmem

# Switch C++ memory allocations to use MicroPython's heap
# cppmem.set_mode(cppmem.MICROPYTHON)

# Copy default files from readonly /system to editable /
default_files = ["main.py", "secrets.py"]
buf = bytearray(256)

for filename in default_files:
    print(f"Copying {filename}")
    try:
        open(f"/{filename}", "r").read()
        open("/system/nocopy", "r").read()
    except OSError:
        with open(f"/system/{filename}", "r") as system_main:
            with open(f"/{filename}", "w") as main:
                # Note: The device filesystem has a readonly /system accessible via MAC
                # And a writeable / that is visible and usable by code
                # The device copies main.py and secrets.py from /system to / on boot.
                # We replicate this behaviour to try and keep /root/system 1:1 with
                # the on-device filesystem. IE: you should be able to copy /root/system
                # to a device and it *should* just work.
                main.write("# DO NOT EDIT THIS FILE!\n")
                main.write(f"# It is auto-copied from: /system/{filename}\n\n")
                while True:
                    length = system_main.readinto(buf)
                    if not length:
                        break
                    main.write(buf[:length])


import picovector
import builtins

# Import PicoSystem module constants to builtins,
# so they are available globally.
for k, v in picovector.__dict__.items():
    if not k.startswith("__"):
        setattr(builtins, k, v)

for k in ("screen", ):
    setattr(builtins, k, getattr(picovector, k))
